// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#ifndef _UI_COMP_TXTBTN_H
#define _UI_COMP_TXTBTN_H

#include "ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT txtBtn
#define UI_COMP_TXTBTN_TXTBTN 0
#define UI_COMP_TXTBTN_BTN 1
#define UI_COMP_TXTBTN_BTNLBL 2
#define _UI_COMP_TXTBTN_NUM 3
lv_obj_t * ui_txtBtn_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
