// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_HomeScreen
void ui_HomeScreen_screen_init(void);
lv_obj_t * ui_HomeScreen;
lv_obj_t * ui_Input1;
lv_obj_t * ui_muteBtn;
lv_obj_t * muteBtnLabel;
void ui_event_muteBtn(lv_event_t * e);
void ui_event_Input1_Input1_Input1Button(lv_event_t * e);
lv_obj_t * ui_Input2;
void ui_event_Input2_Input2_Input2Button(lv_event_t * e);
lv_obj_t * ui_Input3;
void ui_event_Input3_Input3_Input3Button(lv_event_t * e);
lv_obj_t * ui_Input4;
void ui_event_Input4_Input4_Input4Button(lv_event_t * e);
void ui_event_volIndicator(lv_event_t * e);
lv_obj_t * ui_volIndicator;
lv_obj_t * ui_volLabel;
lv_obj_t * ui_trebleSlider;
void ui_event_trebleSlider(lv_event_t * e);
lv_obj_t * ui_trebleLabel;
lv_obj_t * ui_bassSlider;
void ui_event_bassSlider(lv_event_t * e);
lv_obj_t * ui_bassLabel;
lv_obj_t * ui_trebleDownLabel;
lv_obj_t * ui_trebleUpLabel;
lv_obj_t * ui_bassDownLabel;
lv_obj_t * ui_bassUpLabel;
void ui_event_Settings(lv_event_t * e);
lv_obj_t * ui_Settings;
// CUSTOM VARIABLES
lv_obj_t * uic_Input1;
lv_obj_t * uic_Input1_Input1Button;
lv_obj_t * uic_Input1_Input1Label;
lv_obj_t * uic_Input2;
lv_obj_t * uic_Input2_Input2Button;
lv_obj_t * uic_Input2_Input2Label;
lv_obj_t * uic_Input3;
lv_obj_t * uic_Input3_Input3Button;
lv_obj_t * uic_Input3_Input3Label;
lv_obj_t * uic_Input4;
lv_obj_t * uic_Input4_Input4Button;
lv_obj_t * uic_Input4_Input4Label;
lv_obj_t * uic_volIndicator;
lv_obj_t * uic_volLabel;
lv_obj_t * uic_trebleSlider;
lv_obj_t * uic_trebleLabel;
lv_obj_t * uic_bassSlider;
lv_obj_t * uic_bassLabel;
lv_obj_t * uic_trebleDownLabel;
lv_obj_t * uic_trebleUpLabel;
lv_obj_t * uic_bassDownLabel;
lv_obj_t * uic_bassUpLabel;

// SCREEN: ui_SettingsScreen
void ui_SettingsScreen_screen_init(void);
lv_obj_t * ui_SettingsScreen;
void ui_event_Label8(lv_event_t * e);
lv_obj_t * ui_Label8;
lv_obj_t * ui_InputNamesLabel;
void ui_event_Input1Name_txtBtn(lv_event_t * e);
lv_obj_t * ui_Input1Name;
void ui_event_Input1Name_Input1Name_Input1NameButton(lv_event_t * e);
void ui_event_Input2Name_txtBtn(lv_event_t * e);
lv_obj_t * ui_Input2Name;
void ui_event_Input2Name_Input2Name_Input2NameButton(lv_event_t * e);
void ui_event_Input3Name_txtBtn(lv_event_t * e);
lv_obj_t * ui_Input3Name;
void ui_event_Input3Name_Input3Name_Input3NameButton(lv_event_t * e);
void ui_event_Input4Name_txtBtn(lv_event_t * e);
lv_obj_t * ui_Input4Name;
void ui_event_Input4Name_Input4Name_Input4NameButton(lv_event_t * e);
// CUSTOM VARIABLES
lv_obj_t * uic_Input1Name;
lv_obj_t * uic_Input1Name_Input1NameButton;
lv_obj_t * uic_Input1Name_Input1NameLabel;
lv_obj_t * uic_Input2Name_Input2NameButton;
lv_obj_t * uic_Input2Name_Input2NameLabel;
lv_obj_t * uic_Input3Name;
lv_obj_t * uic_Input3Name_Input3NameButton;
lv_obj_t * uic_Input3Name_Input3NameLabel;
lv_obj_t * uic_Input4Name;
lv_obj_t * uic_Input4Name_Input4NameButton;
lv_obj_t * uic_Input4Name_Input4NameLabel;

// SCREEN: ui_TextEntry
void ui_TextEntry_screen_init(void);
lv_obj_t * ui_TextEntry;
lv_obj_t * ui_Keyboard1;
void ui_event_TextEntryPreview(lv_event_t * e);
lv_obj_t * ui_TextEntryPreview;
void ui_event_TextEntryDoneButton(lv_event_t * e);
lv_obj_t * ui_TextEntryDoneButton;
lv_obj_t * ui_TextEntryDoneLabel;
// CUSTOM VARIABLES
lv_obj_t * uic_TextEntry;
lv_obj_t * uic_TextEntryPreview;
lv_obj_t * uic_TextEntryDoneLabel;

extern int input;
extern int dispVol;
extern bool isMuted;
void handleMuteBtn();
extern void handleMute(bool muteState);
void selectInput(int inputInt);
extern void changeInput(int input);
extern void handleVolume(int vol);
extern void handleTreble(int trebleLevel);
extern void handleBass(int trebleLevel);


// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void selectInput(int inputInt){
    switch (inputInt){
        case 0x01:
            _ui_state_modify(ui_comp_get_child(ui_Input4, UI_COMP_TXTBTN_BTN), LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
            _ui_state_modify(ui_comp_get_child(ui_Input3, UI_COMP_TXTBTN_BTN), LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
            _ui_state_modify(ui_comp_get_child(ui_Input2, UI_COMP_TXTBTN_BTN), LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
            _ui_state_modify(ui_comp_get_child(ui_Input1, UI_COMP_TXTBTN_BTN), LV_STATE_CHECKED, _UI_MODIFY_STATE_ADD);
            changeInput(0x01);
            break;
        case 0x02:
            _ui_state_modify(ui_comp_get_child(ui_Input4, UI_COMP_TXTBTN_BTN), LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
            _ui_state_modify(ui_comp_get_child(ui_Input3, UI_COMP_TXTBTN_BTN), LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
            _ui_state_modify(ui_comp_get_child(ui_Input2, UI_COMP_TXTBTN_BTN), LV_STATE_CHECKED, _UI_MODIFY_STATE_ADD);
            _ui_state_modify(ui_comp_get_child(ui_Input1, UI_COMP_TXTBTN_BTN), LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
            changeInput(0x02);
            break;
        case 0x03:
            _ui_state_modify(ui_comp_get_child(ui_Input4, UI_COMP_TXTBTN_BTN), LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
            _ui_state_modify(ui_comp_get_child(ui_Input3, UI_COMP_TXTBTN_BTN), LV_STATE_CHECKED, _UI_MODIFY_STATE_ADD);
            _ui_state_modify(ui_comp_get_child(ui_Input2, UI_COMP_TXTBTN_BTN), LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
            _ui_state_modify(ui_comp_get_child(ui_Input1, UI_COMP_TXTBTN_BTN), LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
            changeInput(0x03);
            break;
        case 0x04:
            _ui_state_modify(ui_comp_get_child(ui_Input4, UI_COMP_TXTBTN_BTN), LV_STATE_CHECKED, _UI_MODIFY_STATE_ADD);
            _ui_state_modify(ui_comp_get_child(ui_Input3, UI_COMP_TXTBTN_BTN), LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
            _ui_state_modify(ui_comp_get_child(ui_Input2, UI_COMP_TXTBTN_BTN), LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
            _ui_state_modify(ui_comp_get_child(ui_Input1, UI_COMP_TXTBTN_BTN), LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
            changeInput(0x04);
            break;
    }
}

void handleMuteBtn(){
    if (isMuted) {
        _ui_state_modify(ui_comp_get_child(ui_muteBtn, UI_COMP_TXTBTN_BTN), LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        handleMute(false);

    } else {
        _ui_state_modify(ui_comp_get_child(ui_muteBtn, UI_COMP_TXTBTN_BTN), LV_STATE_CHECKED, _UI_MODIFY_STATE_ADD);
        handleMute(true);
    }
}

void ui_event_muteBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        handleMuteBtn();
    }
}


void ui_event_Input1_Input1_Input1Button(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        selectInput(1);
    }
}

void ui_event_Input2_Input2_Input2Button(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        selectInput(2);
    }
}

void ui_event_Input3_Input3_Input3Button(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        selectInput(3);
    }
}

void ui_event_Input4_Input4_Input4Button(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        selectInput(4);
    }
}

void ui_event_volIndicator(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_arc_set_text_value(ui_volLabel, target, "", "");
        handleVolume(lv_arc_get_value(target));
    }
}

void ui_event_trebleSlider(lv_event_t * e){
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED){
        handleTreble(lv_slider_get_value(target));
    }
}

void ui_event_bassSlider(lv_event_t * e){
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED){
        handleBass(lv_slider_get_value(target));
    }
}

void ui_event_Settings(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_SettingsScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_SettingsScreen_screen_init);
    }
}

void ui_event_Label8(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_HomeScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_HomeScreen_screen_init);
    }
}

void ui_event_Input1Name_txtBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        inputRename(e);
    }
}

void ui_event_Input1Name_Input1Name_Input1NameButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_TextEntry, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_TextEntry_screen_init);
    }
    if(event_code == LV_EVENT_CLICKED) {
        _ui_label_set_property(ui_comp_get_child(ui_Input1Name, UI_COMP_TXTBTN_BTNLBL), _UI_LABEL_PROPERTY_TEXT, "banana!");
    }
}

void ui_event_Input2Name_txtBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        inputRename(e);
    }
}

void ui_event_Input2Name_Input2Name_Input2NameButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_TextEntry, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_TextEntry_screen_init);
    }
    if(event_code == LV_EVENT_CLICKED) {
        _ui_label_set_property(ui_comp_get_child(ui_Input2Name, UI_COMP_TXTBTN_BTNLBL), _UI_LABEL_PROPERTY_TEXT, "banana!");
    }
}

void ui_event_Input3Name_txtBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        inputRename(e);
    }
}

void ui_event_Input3Name_Input3Name_Input3NameButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_TextEntry, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_TextEntry_screen_init);
    }
    if(event_code == LV_EVENT_CLICKED) {
        _ui_label_set_property(ui_comp_get_child(ui_Input3Name, UI_COMP_TXTBTN_BTNLBL), _UI_LABEL_PROPERTY_TEXT, "banana!");
    }
}

void ui_event_Input4Name_txtBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        inputRename(e);
    }
}

void ui_event_Input4Name_Input4Name_Input4NameButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_TextEntry, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_TextEntry_screen_init);
    }
    if(event_code == LV_EVENT_CLICKED) {
        _ui_label_set_property(ui_comp_get_child(ui_Input4Name, UI_COMP_TXTBTN_BTNLBL), _UI_LABEL_PROPERTY_TEXT, "banana!");
    }
}

void ui_event_TextEntryPreview(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_label_set_property(ui_trebleUpLabel, _UI_LABEL_PROPERTY_TEXT, "");
    }
}

void ui_event_TextEntryDoneButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_SettingsScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_SettingsScreen_screen_init);
    }
    if(event_code == LV_EVENT_CLICKED) {
        renameDone(e);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    LV_EVENT_GET_COMP_CHILD = lv_event_register_id();

    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_HomeScreen_screen_init();
    ui_SettingsScreen_screen_init();
    ui_TextEntry_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_HomeScreen);
}
