// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_comp.h"
#include "ui_comp_hook.h"
#include "ui_events.h"

// SCREEN: ui_HomeScreen
void ui_HomeScreen_screen_init(void);
extern lv_obj_t * ui_HomeScreen;
extern lv_obj_t * ui_Input1;
void ui_event_Input1_Input1_Input1Button(lv_event_t * e);
void selectInput(int inputInt);
extern lv_obj_t * ui_Input2;
void ui_event_Input2_Input2_Input2Button(lv_event_t * e);
extern lv_obj_t * ui_Input3;
void ui_event_Input3_Input3_Input3Button(lv_event_t * e);
extern lv_obj_t * ui_Input4;
void ui_event_Input4_Input4_Input4Button(lv_event_t * e);
void ui_event_volIndicator(lv_event_t * e);
extern lv_obj_t * ui_volIndicator;
extern lv_obj_t * ui_volLabel;
extern lv_obj_t * ui_trebleSlider;
extern lv_obj_t * ui_trebleLabel;
extern lv_obj_t * ui_bassSlider;
extern lv_obj_t * ui_bassLabel;
extern lv_obj_t * ui_trebleDownLabel;
extern lv_obj_t * ui_trebleUpLabel;
extern lv_obj_t * ui_bassDownLabel;
extern lv_obj_t * ui_bassUpLabel;
void ui_event_Settings(lv_event_t * e);
extern lv_obj_t * ui_Settings;
// CUSTOM VARIABLES
extern lv_obj_t * uic_Input1;
extern lv_obj_t * uic_Input1_Input1Button;
extern lv_obj_t * uic_Input1_Input1Label;
extern lv_obj_t * uic_Input2;
extern lv_obj_t * uic_Input2_Input2Button;
extern lv_obj_t * uic_Input2_Input2Label;
extern lv_obj_t * uic_Input3;
extern lv_obj_t * uic_Input3_Input3Button;
extern lv_obj_t * uic_Input3_Input3Label;
extern lv_obj_t * uic_Input4;
extern lv_obj_t * uic_Input4_Input4Button;
extern lv_obj_t * uic_Input4_Input4Label;
extern lv_obj_t * uic_volIndicator;
extern lv_obj_t * uic_volLabel;
extern lv_obj_t * uic_trebleSlider;
extern lv_obj_t * uic_trebleLabel;
extern lv_obj_t * uic_bassSlider;
extern lv_obj_t * uic_bassLabel;
extern lv_obj_t * uic_trebleDownLabel;
extern lv_obj_t * uic_trebleUpLabel;
extern lv_obj_t * uic_bassDownLabel;
extern lv_obj_t * uic_bassUpLabel;

// SCREEN: ui_SettingsScreen
void ui_SettingsScreen_screen_init(void);
extern lv_obj_t * ui_SettingsScreen;
void ui_event_Label8(lv_event_t * e);
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_InputNamesLabel;
void ui_event_Input1Name_txtBtn(lv_event_t * e);
extern lv_obj_t * ui_Input1Name;
void ui_event_Input1Name_Input1Name_Input1NameButton(lv_event_t * e);
void ui_event_Input2Name_txtBtn(lv_event_t * e);
extern lv_obj_t * ui_Input2Name;
void ui_event_Input2Name_Input2Name_Input2NameButton(lv_event_t * e);
void ui_event_Input3Name_txtBtn(lv_event_t * e);
extern lv_obj_t * ui_Input3Name;
void ui_event_Input3Name_Input3Name_Input3NameButton(lv_event_t * e);
void ui_event_Input4Name_txtBtn(lv_event_t * e);
extern lv_obj_t * ui_Input4Name;
void ui_event_Input4Name_Input4Name_Input4NameButton(lv_event_t * e);
// CUSTOM VARIABLES
extern lv_obj_t * uic_Input1Name;
extern lv_obj_t * uic_Input1Name_Input1NameButton;
extern lv_obj_t * uic_Input1Name_Input1NameLabel;
extern lv_obj_t * uic_Input2Name_Input2NameButton;
extern lv_obj_t * uic_Input2Name_Input2NameLabel;
extern lv_obj_t * uic_Input3Name;
extern lv_obj_t * uic_Input3Name_Input3NameButton;
extern lv_obj_t * uic_Input3Name_Input3NameLabel;
extern lv_obj_t * uic_Input4Name;
extern lv_obj_t * uic_Input4Name_Input4NameButton;
extern lv_obj_t * uic_Input4Name_Input4NameLabel;

// SCREEN: ui_TextEntry
void ui_TextEntry_screen_init(void);
extern lv_obj_t * ui_TextEntry;
extern lv_obj_t * ui_Keyboard1;
void ui_event_TextEntryPreview(lv_event_t * e);
extern lv_obj_t * ui_TextEntryPreview;
void ui_event_TextEntryDoneButton(lv_event_t * e);
extern lv_obj_t * ui_TextEntryDoneButton;
extern lv_obj_t * ui_TextEntryDoneLabel;
// CUSTOM VARIABLES
extern lv_obj_t * uic_TextEntry;
extern lv_obj_t * uic_TextEntryPreview;
extern lv_obj_t * uic_TextEntryDoneLabel;

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
