// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

// COMPONENT txtBtn

lv_obj_t * ui_txtBtn_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_txtBtn;
    cui_txtBtn = lv_obj_create(comp_parent);
    lv_obj_remove_style_all(cui_txtBtn);
    lv_obj_set_width(cui_txtBtn, 121);
    lv_obj_set_height(cui_txtBtn, 61);
    lv_obj_set_x(cui_txtBtn, -92);
    lv_obj_set_y(cui_txtBtn, -83);
    lv_obj_set_align(cui_txtBtn, LV_ALIGN_CENTER);
    lv_obj_clear_flag(cui_txtBtn, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t * cui_btn;
    cui_btn = lv_btn_create(cui_txtBtn);
    lv_obj_set_width(cui_btn, 100);
    lv_obj_set_height(cui_btn, 50);
    lv_obj_set_x(cui_btn, -1);
    lv_obj_set_y(cui_btn, 0);
    lv_obj_set_align(cui_btn, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_btn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(cui_btn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_color(cui_btn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_btn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_btn, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_btnLbl;
    cui_btnLbl = lv_label_create(cui_txtBtn);
    lv_obj_set_width(cui_btnLbl, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_btnLbl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_btnLbl, -1);
    lv_obj_set_y(cui_btnLbl, -1);
    lv_obj_set_align(cui_btnLbl, LV_ALIGN_CENTER);
    lv_label_set_text(cui_btnLbl, "Text Here");
    lv_obj_set_style_text_font(cui_btnLbl, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);


    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_TXTBTN_NUM);
    children[UI_COMP_TXTBTN_TXTBTN] = cui_txtBtn;
    children[UI_COMP_TXTBTN_BTN] = cui_btn;
    children[UI_COMP_TXTBTN_BTNLBL] = cui_btnLbl;
    lv_obj_add_event_cb(cui_txtBtn, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_txtBtn, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_txtBtn_create_hook(cui_txtBtn);
    return cui_txtBtn;
}

