// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_HomeScreen_screen_init(void)
{
    ui_HomeScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_HomeScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_muteBtn = ui_txtBtn_create(ui_HomeScreen);
    lv_obj_set_x(ui_muteBtn, 90);
    lv_obj_set_y(ui_muteBtn, -20);
    lv_label_set_text(ui_comp_get_child(ui_muteBtn, UI_COMP_TXTBTN_BTNLBL), "Mute");

    ui_Input1 = ui_txtBtn_create(ui_HomeScreen);
    lv_obj_set_x(ui_Input1, -166);
    lv_obj_set_y(ui_Input1, -113);

    lv_label_set_text(ui_comp_get_child(ui_Input1, UI_COMP_TXTBTN_BTNLBL), "DAC");

    ui_Input2 = ui_txtBtn_create(ui_HomeScreen);
    lv_obj_set_x(ui_Input2, -166);
    lv_obj_set_y(ui_Input2, -38);

    lv_label_set_text(ui_comp_get_child(ui_Input2, UI_COMP_TXTBTN_BTNLBL), "CMPTR");

    ui_Input3 = ui_txtBtn_create(ui_HomeScreen);
    lv_obj_set_x(ui_Input3, -165);
    lv_obj_set_y(ui_Input3, 35);

    lv_label_set_text(ui_comp_get_child(ui_Input3, UI_COMP_TXTBTN_BTNLBL), "CD");

    ui_Input4 = ui_txtBtn_create(ui_HomeScreen);
    lv_obj_set_x(ui_Input4, -165);
    lv_obj_set_y(ui_Input4, 107);

    lv_label_set_text(ui_comp_get_child(ui_Input4, UI_COMP_TXTBTN_BTNLBL), "AUX");

    ui_volIndicator = lv_bar_create(ui_HomeScreen);
    lv_obj_set_width(ui_volIndicator, 202);
    lv_obj_set_height(ui_volIndicator, 20);
    lv_obj_set_x(ui_volIndicator, 78);
    lv_obj_set_y(ui_volIndicator, -105);
    lv_obj_set_align(ui_volIndicator, LV_ALIGN_CENTER);
    lv_bar_set_value(ui_volIndicator, 50, LV_ANIM_OFF);

    ui_volLabel = lv_label_create(ui_HomeScreen);
    lv_obj_set_width(ui_volLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_volLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_volLabel, 185);
    lv_obj_set_y(ui_volLabel, -20);
    lv_obj_set_align(ui_volLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_volLabel, "50");
    lv_obj_set_style_text_font(ui_volLabel, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);


    lv_obj_add_event_cb(ui_comp_get_child(ui_muteBtn, UI_COMP_TXTBTN_BTN), ui_event_muteBtn, LV_EVENT_ALL,
                        NULL);
    lv_obj_add_event_cb(ui_comp_get_child(ui_Input1, UI_COMP_TXTBTN_BTN), ui_event_Input1_Input1_Input1Button, LV_EVENT_ALL,
                        NULL);
    lv_obj_add_event_cb(ui_comp_get_child(ui_Input2, UI_COMP_TXTBTN_BTN), ui_event_Input2_Input2_Input2Button, LV_EVENT_ALL,
                        NULL);
    lv_obj_add_event_cb(ui_comp_get_child(ui_Input3, UI_COMP_TXTBTN_BTN), ui_event_Input3_Input3_Input3Button, LV_EVENT_ALL,
                        NULL);
    lv_obj_add_event_cb(ui_comp_get_child(ui_Input4, UI_COMP_TXTBTN_BTN), ui_event_Input4_Input4_Input4Button, LV_EVENT_ALL,
                        NULL);
    lv_obj_add_event_cb(ui_volIndicator, ui_event_volIndicator, LV_EVENT_ALL, NULL);
    uic_Input1 = ui_Input1;
    uic_Input1_Input1Button = ui_comp_get_child(ui_Input1, UI_COMP_TXTBTN_BTN);
    uic_Input1_Input1Label = ui_comp_get_child(ui_Input1, UI_COMP_TXTBTN_BTNLBL);
    uic_Input2 = ui_Input2;
    uic_Input2_Input2Button = ui_comp_get_child(ui_Input2, UI_COMP_TXTBTN_BTN);
    uic_Input2_Input2Label = ui_comp_get_child(ui_Input2, UI_COMP_TXTBTN_BTNLBL);
    uic_Input3 = ui_Input3;
    uic_Input3_Input3Button = ui_comp_get_child(ui_Input3, UI_COMP_TXTBTN_BTN);
    uic_Input3_Input3Label = ui_comp_get_child(ui_Input3, UI_COMP_TXTBTN_BTNLBL);
    uic_Input4 = ui_Input4;
    uic_Input4_Input4Button = ui_comp_get_child(ui_Input4, UI_COMP_TXTBTN_BTN);
    uic_Input4_Input4Label = ui_comp_get_child(ui_Input4, UI_COMP_TXTBTN_BTNLBL);
    uic_volIndicator = ui_volIndicator;
    uic_volLabel = ui_volLabel;

}
