// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_HomeScreen_screen_init(void)
{
    ui_HomeScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_HomeScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Input1 = ui_txtBtn_create(ui_HomeScreen);
    lv_obj_set_x(ui_Input1, -166);
    lv_obj_set_y(ui_Input1, -113);

    lv_label_set_text(ui_comp_get_child(ui_Input1, UI_COMP_TXTBTN_BTNLBL), "Input 1");

    ui_Input2 = ui_txtBtn_create(ui_HomeScreen);
    lv_obj_set_x(ui_Input2, -166);
    lv_obj_set_y(ui_Input2, -38);

    lv_label_set_text(ui_comp_get_child(ui_Input2, UI_COMP_TXTBTN_BTNLBL), "Input 2");

    ui_Input3 = ui_txtBtn_create(ui_HomeScreen);
    lv_obj_set_x(ui_Input3, -165);
    lv_obj_set_y(ui_Input3, 35);

    lv_label_set_text(ui_comp_get_child(ui_Input3, UI_COMP_TXTBTN_BTNLBL), "Input 3");

    ui_Input4 = ui_txtBtn_create(ui_HomeScreen);
    lv_obj_set_x(ui_Input4, -165);
    lv_obj_set_y(ui_Input4, 107);

    lv_label_set_text(ui_comp_get_child(ui_Input4, UI_COMP_TXTBTN_BTNLBL), "Input 4");

    ui_volIndicator = lv_arc_create(ui_HomeScreen);
    lv_obj_set_width(ui_volIndicator, 202);
    lv_obj_set_height(ui_volIndicator, 212);
    lv_obj_set_x(ui_volIndicator, 78);
    lv_obj_set_y(ui_volIndicator, -27);
    lv_obj_set_align(ui_volIndicator, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_volIndicator, 50);

    ui_volLabel = lv_label_create(ui_HomeScreen);
    lv_obj_set_width(ui_volLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_volLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_volLabel, 76);
    lv_obj_set_y(ui_volLabel, -33);
    lv_obj_set_align(ui_volLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_volLabel, "50");
    lv_obj_set_style_text_font(ui_volLabel, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_trebleSlider = lv_slider_create(ui_HomeScreen);
    lv_slider_set_range(ui_trebleSlider, -10, 10);
    lv_slider_set_mode(ui_trebleSlider, LV_SLIDER_MODE_SYMMETRICAL);
    lv_slider_set_value(ui_trebleSlider, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_trebleSlider) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_trebleSlider, 0,
                                                                                                 LV_ANIM_OFF);
    lv_obj_set_width(ui_trebleSlider, 205);
    lv_obj_set_height(ui_trebleSlider, 10);
    lv_obj_set_x(ui_trebleSlider, 77);
    lv_obj_set_y(ui_trebleSlider, 86);
    lv_obj_set_align(ui_trebleSlider, LV_ALIGN_CENTER);

    ui_trebleLabel = lv_label_create(ui_HomeScreen);
    lv_obj_set_width(ui_trebleLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_trebleLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_trebleLabel, 78);
    lv_obj_set_y(ui_trebleLabel, 60);
    lv_obj_set_align(ui_trebleLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_trebleLabel, "Treble");

    ui_bassSlider = lv_slider_create(ui_HomeScreen);
    lv_slider_set_range(ui_bassSlider, -10, 10);
    lv_slider_set_mode(ui_bassSlider, LV_SLIDER_MODE_SYMMETRICAL);
    lv_slider_set_value(ui_bassSlider, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_bassSlider) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_bassSlider, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_bassSlider, 209);
    lv_obj_set_height(ui_bassSlider, 10);
    lv_obj_set_x(ui_bassSlider, 78);
    lv_obj_set_y(ui_bassSlider, 130);
    lv_obj_set_align(ui_bassSlider, LV_ALIGN_CENTER);

    ui_bassLabel = lv_label_create(ui_HomeScreen);
    lv_obj_set_width(ui_bassLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_bassLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_bassLabel, 77);
    lv_obj_set_y(ui_bassLabel, 108);
    lv_obj_set_align(ui_bassLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_bassLabel, "Bass");

    ui_trebleDownLabel = lv_label_create(ui_HomeScreen);
    lv_obj_set_width(ui_trebleDownLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_trebleDownLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_trebleDownLabel, -37);
    lv_obj_set_y(ui_trebleDownLabel, 84);
    lv_obj_set_align(ui_trebleDownLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_trebleDownLabel, "-");

    ui_trebleUpLabel = lv_label_create(ui_HomeScreen);
    lv_obj_set_width(ui_trebleUpLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_trebleUpLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_trebleUpLabel, 192);
    lv_obj_set_y(ui_trebleUpLabel, 85);
    lv_obj_set_align(ui_trebleUpLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_trebleUpLabel, "+");

    ui_bassDownLabel = lv_label_create(ui_HomeScreen);
    lv_obj_set_width(ui_bassDownLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_bassDownLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_bassDownLabel, -35);
    lv_obj_set_y(ui_bassDownLabel, 129);
    lv_obj_set_align(ui_bassDownLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_bassDownLabel, "-");

    ui_bassUpLabel = lv_label_create(ui_HomeScreen);
    lv_obj_set_width(ui_bassUpLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_bassUpLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_bassUpLabel, 194);
    lv_obj_set_y(ui_bassUpLabel, 131);
    lv_obj_set_align(ui_bassUpLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_bassUpLabel, "+");

    ui_Settings = lv_label_create(ui_HomeScreen);
    lv_obj_set_width(ui_Settings, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Settings, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Settings, 208);
    lv_obj_set_y(ui_Settings, -136);
    lv_obj_set_align(ui_Settings, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Settings, "Set");
    lv_obj_add_flag(ui_Settings, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_set_style_text_font(ui_Settings, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_comp_get_child(ui_Input1, UI_COMP_TXTBTN_BTN), ui_event_Input1_Input1_Input1Button, LV_EVENT_ALL,
                        NULL);
    lv_obj_add_event_cb(ui_comp_get_child(ui_Input2, UI_COMP_TXTBTN_BTN), ui_event_Input2_Input2_Input2Button, LV_EVENT_ALL,
                        NULL);
    lv_obj_add_event_cb(ui_comp_get_child(ui_Input3, UI_COMP_TXTBTN_BTN), ui_event_Input3_Input3_Input3Button, LV_EVENT_ALL,
                        NULL);
    lv_obj_add_event_cb(ui_comp_get_child(ui_Input4, UI_COMP_TXTBTN_BTN), ui_event_Input4_Input4_Input4Button, LV_EVENT_ALL,
                        NULL);
    lv_obj_add_event_cb(ui_volIndicator, ui_event_volIndicator, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Settings, ui_event_Settings, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_trebleSlider, ui_event_trebleSlider, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_bassSlider, ui_event_bassSlider, LV_EVENT_ALL, NULL);
    uic_Input1 = ui_Input1;
    uic_Input1_Input1Button = ui_comp_get_child(ui_Input1, UI_COMP_TXTBTN_BTN);
    uic_Input1_Input1Label = ui_comp_get_child(ui_Input1, UI_COMP_TXTBTN_BTNLBL);
    uic_Input2 = ui_Input2;
    uic_Input2_Input2Button = ui_comp_get_child(ui_Input2, UI_COMP_TXTBTN_BTN);
    uic_Input2_Input2Label = ui_comp_get_child(ui_Input2, UI_COMP_TXTBTN_BTNLBL);
    uic_Input3 = ui_Input3;
    uic_Input3_Input3Button = ui_comp_get_child(ui_Input3, UI_COMP_TXTBTN_BTN);
    uic_Input3_Input3Label = ui_comp_get_child(ui_Input3, UI_COMP_TXTBTN_BTNLBL);
    uic_Input4 = ui_Input4;
    uic_Input4_Input4Button = ui_comp_get_child(ui_Input4, UI_COMP_TXTBTN_BTN);
    uic_Input4_Input4Label = ui_comp_get_child(ui_Input4, UI_COMP_TXTBTN_BTNLBL);
    uic_volIndicator = ui_volIndicator;
    uic_volLabel = ui_volLabel;
    uic_trebleSlider = ui_trebleSlider;
    uic_trebleLabel = ui_trebleLabel;
    uic_bassSlider = ui_bassSlider;
    uic_bassLabel = ui_bassLabel;
    uic_trebleDownLabel = ui_trebleDownLabel;
    uic_trebleUpLabel = ui_trebleUpLabel;
    uic_bassDownLabel = ui_bassDownLabel;
    uic_bassUpLabel = ui_bassUpLabel;

}
