// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_TextEntry_screen_init(void)
{
    ui_TextEntry = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_TextEntry, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Keyboard1 = lv_keyboard_create(ui_TextEntry);
    lv_obj_set_width(ui_Keyboard1, 467);
    lv_obj_set_height(ui_Keyboard1, 183);
    lv_obj_set_x(ui_Keyboard1, -3);
    lv_obj_set_y(ui_Keyboard1, 63);
    lv_obj_set_align(ui_Keyboard1, LV_ALIGN_CENTER);

    ui_TextEntryPreview = lv_textarea_create(ui_TextEntry);
    lv_obj_set_width(ui_TextEntryPreview, 275);
    lv_obj_set_height(ui_TextEntryPreview, 98);
    lv_obj_set_x(ui_TextEntryPreview, -87);
    lv_obj_set_y(ui_TextEntryPreview, -94);
    lv_obj_set_align(ui_TextEntryPreview, LV_ALIGN_CENTER);
    lv_textarea_set_max_length(ui_TextEntryPreview, 12);
    lv_textarea_set_placeholder_text(ui_TextEntryPreview, "Text...");

    ui_TextEntryDoneButton = lv_btn_create(ui_TextEntry);
    lv_obj_set_width(ui_TextEntryDoneButton, 108);
    lv_obj_set_height(ui_TextEntryDoneButton, 68);
    lv_obj_set_x(ui_TextEntryDoneButton, 145);
    lv_obj_set_y(ui_TextEntryDoneButton, -94);
    lv_obj_set_align(ui_TextEntryDoneButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_TextEntryDoneButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_TextEntryDoneButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TextEntryDoneLabel = lv_label_create(ui_TextEntry);
    lv_obj_set_width(ui_TextEntryDoneLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TextEntryDoneLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TextEntryDoneLabel, 146);
    lv_obj_set_y(ui_TextEntryDoneLabel, -94);
    lv_obj_set_align(ui_TextEntryDoneLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TextEntryDoneLabel, "Done");

    lv_keyboard_set_textarea(ui_Keyboard1, ui_TextEntryPreview);
    lv_obj_add_event_cb(ui_TextEntryPreview, ui_event_TextEntryPreview, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TextEntryDoneButton, ui_event_TextEntryDoneButton, LV_EVENT_ALL, NULL);
    uic_TextEntry = ui_TextEntry;
    uic_TextEntryPreview = ui_TextEntryPreview;
    uic_TextEntryDoneLabel = ui_TextEntryDoneLabel;

}
