// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "ui.h"

void ui_SettingsScreen_screen_init(void)
{
    ui_SettingsScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_SettingsScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label8 = lv_label_create(ui_SettingsScreen);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label8, -214);
    lv_obj_set_y(ui_Label8, -125);
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "X");
    lv_obj_add_flag(ui_Label8, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_set_style_text_font(ui_Label8, &lv_font_montserrat_42, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_InputNamesLabel = lv_label_create(ui_SettingsScreen);
    lv_obj_set_width(ui_InputNamesLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_InputNamesLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_InputNamesLabel, 7);
    lv_obj_set_y(ui_InputNamesLabel, -144);
    lv_obj_set_align(ui_InputNamesLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_InputNamesLabel, "Input Naming");

    ui_Input1Name = ui_txtBtn_create(ui_SettingsScreen);
    lv_obj_set_x(ui_Input1Name, -83);
    lv_obj_set_y(ui_Input1Name, -40);

    ui_Input2Name = ui_txtBtn_create(ui_SettingsScreen);
    lv_obj_set_x(ui_Input2Name, 84);
    lv_obj_set_y(ui_Input2Name, -41);

    ui_Input3Name = ui_txtBtn_create(ui_SettingsScreen);
    lv_obj_set_x(ui_Input3Name, -83);
    lv_obj_set_y(ui_Input3Name, 56);

    ui_Input4Name = ui_txtBtn_create(ui_SettingsScreen);
    lv_obj_set_x(ui_Input4Name, 86);
    lv_obj_set_y(ui_Input4Name, 59);

    lv_obj_add_event_cb(ui_Label8, ui_event_Label8, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_comp_get_child(ui_Input1Name, UI_COMP_TXTBTN_BTN),
                        ui_event_Input1Name_Input1Name_Input1NameButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Input1Name, ui_event_Input1Name_txtBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_comp_get_child(ui_Input2Name, UI_COMP_TXTBTN_BTN),
                        ui_event_Input2Name_Input2Name_Input2NameButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Input2Name, ui_event_Input2Name_txtBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_comp_get_child(ui_Input3Name, UI_COMP_TXTBTN_BTN),
                        ui_event_Input3Name_Input3Name_Input3NameButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Input3Name, ui_event_Input3Name_txtBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_comp_get_child(ui_Input4Name, UI_COMP_TXTBTN_BTN),
                        ui_event_Input4Name_Input4Name_Input4NameButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Input4Name, ui_event_Input4Name_txtBtn, LV_EVENT_ALL, NULL);
    uic_Input1Name = ui_Input1Name;
    uic_Input1Name_Input1NameButton = ui_comp_get_child(ui_Input1Name, UI_COMP_TXTBTN_BTN);
    uic_Input1Name_Input1NameLabel = ui_comp_get_child(ui_Input1Name, UI_COMP_TXTBTN_BTNLBL);
    uic_Input2Name_Input2NameButton = ui_comp_get_child(ui_Input2Name, UI_COMP_TXTBTN_BTN);
    uic_Input2Name_Input2NameLabel = ui_comp_get_child(ui_Input2Name, UI_COMP_TXTBTN_BTNLBL);
    uic_Input3Name = ui_Input3Name;
    uic_Input3Name_Input3NameButton = ui_comp_get_child(ui_Input3Name, UI_COMP_TXTBTN_BTN);
    uic_Input3Name_Input3NameLabel = ui_comp_get_child(ui_Input3Name, UI_COMP_TXTBTN_BTNLBL);
    uic_Input4Name = ui_Input4Name;
    uic_Input4Name_Input4NameButton = ui_comp_get_child(ui_Input4Name, UI_COMP_TXTBTN_BTN);
    uic_Input4Name_Input4NameLabel = ui_comp_get_child(ui_Input4Name, UI_COMP_TXTBTN_BTNLBL);

}
